package gematria

import (
	"database/sql"
	"fmt"

	_ "modernc.org/sqlite"
)

// sqliteWordSource is an unexported WordSource backed by a pre-indexed SQLite
// database generated by "gematria index --format sqlite".
type sqliteWordSource struct {
	db *sql.DB
}

// Compile-time assertions.
var _ WordSource = (*sqliteWordSource)(nil)
var _ interface{ Close() error } = (*sqliteWordSource)(nil)

// OpenSQLiteWordSource opens an existing SQLite word-list database.
// The database must have been produced by "gematria index --format sqlite".
// Callers should check whether the returned WordSource also implements
// io.Closer and call Close when done.
func OpenSQLiteWordSource(path string) (WordSource, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("gematria: open sqlite %q: %w", path, err)
	}

	// Verify the file is reachable and non-empty.
	if err := db.Ping(); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("gematria: sqlite ping %q: %w", path, err)
	}

	// Schema verification: ensure both required tables exist.
	if err := verifySQLiteSchema(db); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("gematria: sqlite schema %q: %w", path, err)
	}

	return &sqliteWordSource{db: db}, nil
}

// verifySQLiteSchema checks that both tables required by the gematria schema
// exist in the database. Returns an error with a descriptive message if not.
func verifySQLiteSchema(db *sql.DB) error {
	tables := []string{"words", "word_values"}
	for _, table := range tables {
		var name string
		err := db.QueryRow(
			`SELECT name FROM sqlite_master WHERE type='table' AND name=?`,
			table,
		).Scan(&name)
		if err != nil {
			return fmt.Errorf("missing table %q (is this a gematria index database?)", table)
		}
	}
	return nil
}

// FindByValue queries the database for words whose gematria value under system
// equals value. Returns at most limit Words. hasMore is true when additional
// matching words exist beyond the returned slice.
func (s *sqliteWordSource) FindByValue(value int, system System, limit int) ([]Word, bool, error) {
	rows, err := s.db.Query(
		`SELECT w.hebrew, w.transliteration, w.meaning
		 FROM words w
		 JOIN word_values v ON v.word_id = w.id
		 WHERE v.system = ? AND v.value = ?
		 LIMIT ?`,
		string(system), value, limit+1,
	)
	if err != nil {
		return nil, false, fmt.Errorf("gematria: sqlite query: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var results []Word
	for rows.Next() {
		var w Word
		if err := rows.Scan(&w.Hebrew, &w.Transliteration, &w.Meaning); err != nil {
			return nil, false, fmt.Errorf("gematria: sqlite scan: %w", err)
		}
		results = append(results, w)
	}
	if err := rows.Err(); err != nil {
		return nil, false, fmt.Errorf("gematria: sqlite rows: %w", err)
	}

	if len(results) > limit {
		return results[:limit], true, nil
	}
	return results, false, nil
}

// Close releases the underlying database connection.
func (s *sqliteWordSource) Close() error {
	return s.db.Close()
}

// WriteIndexSQLite creates (or overwrites) a SQLite database at path containing
// pre-computed gematria values for all four systems. It is the write counterpart
// of OpenSQLiteWordSource and produces a file that OpenSQLiteWordSource can read.
//
// Words whose Hebrew text fails Compute for a given system are indexed for the
// remaining systems; errors are silently skipped.
//
// Returns (count, error) where count is the number of words successfully inserted.
func WriteIndexSQLite(path string, words []Word) (int, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return 0, fmt.Errorf("gematria: create sqlite %q: %w", path, err)
	}
	defer func() { _ = db.Close() }()

	_, err = db.Exec(`
		CREATE TABLE IF NOT EXISTS words (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			hebrew TEXT NOT NULL,
			transliteration TEXT NOT NULL DEFAULT '',
			meaning TEXT NOT NULL DEFAULT ''
		);
		CREATE TABLE IF NOT EXISTS word_values (
			word_id INTEGER NOT NULL REFERENCES words(id),
			system TEXT NOT NULL,
			value INTEGER NOT NULL
		);
		CREATE INDEX IF NOT EXISTS idx_word_values ON word_values(system, value);
	`)
	if err != nil {
		return 0, fmt.Errorf("gematria: sqlite schema: %w", err)
	}

	tx, err := db.Begin()
	if err != nil {
		return 0, fmt.Errorf("gematria: sqlite begin: %w", err)
	}

	systems := ValidSystems()
	count := 0

	for _, w := range words {
		res, err := tx.Exec(
			`INSERT INTO words (hebrew, transliteration, meaning) VALUES (?, ?, ?)`,
			w.Hebrew, w.Transliteration, w.Meaning,
		)
		if err != nil {
			_ = tx.Rollback()
			return 0, fmt.Errorf("gematria: sqlite insert word: %w", err)
		}
		wordID, _ := res.LastInsertId()
		for _, sys := range systems {
			result, err := Compute(w.Hebrew, sys)
			if err != nil {
				continue
			}
			_, err = tx.Exec(
				`INSERT INTO word_values (word_id, system, value) VALUES (?, ?, ?)`,
				wordID, string(sys), result.Total,
			)
			if err != nil {
				_ = tx.Rollback()
				return 0, fmt.Errorf("gematria: sqlite insert value: %w", err)
			}
		}
		count++
	}

	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("gematria: sqlite commit: %w", err)
	}
	return count, nil
}
